language: cpp

sudo: false

env:
  global:
    - PREFIX: $(pwd)/install
    - JOBS: "8"

matrix:
  include:
     # OS X
     - os: osx
       # https://docs.travis-ci.com/user/languages/objective-c/#Supported-OS-X-iOS-SDK-versions
       osx_image: xcode7.2 # upgrades clang from 6 -> 7
       compiler: clang
     # Linux
     - os: linux
       compiler: clang

cache:
  directories:
  - $HOME/.ccache
  apt: true

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
     - llvm-toolchain-precise-3.6
    packages:
     - time
     - clang-3.6
     - libedit-dev

install:
 - git clone --depth=1 https://github.com/mapbox/mason.git ~/.mason
 - ~/.mason/mason install cmake 3.2.2
 - ~/.mason/mason link cmake 3.2.2
 - export PATH=$(pwd)/mason_packages/.link/bin:${PATH}
 - git clone --depth=1 git://github.com/martine/ninja.git;
 - cd ninja;
 - export PATH=$(pwd):${PATH};
 - ./configure.py --bootstrap;
 - cd ../;
 - if [[ $(uname -s) == 'Linux' ]]; then
     echo '#!/bin/bash' > ./cxx_compiler;
     echo 'ccache clang++-3.6 -Qunused-arguments "$@"' >> ./cxx_compiler;
     chmod +x ./cxx_compiler;
     export CXX="$(pwd)/cxx_compiler";
     echo 'ccache clang-3.6 -Qunused-arguments "$@"' >> ./c_compiler;
     chmod +x ./c_compiler;
     export CC="$(pwd)/c_compiler";
   fi
 - ./build.sh # setup

before_script:
 - true
 # ./build.sh # update

script:
 - if [[ -f $PREFIX/bin/clang ]]; then file $PREFIX/bin/clang; fi;
 - if [[ -f $PREFIX/bin/lldb ]]; then file $PREFIX/bin/lldb; fi;
