language: cpp

sudo: false

compiler:
 - clang

env:
  global:
    - PREFIX=$(pwd)/install
    - JOBS="12"

before_install:
 # https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
 - sudo apt-get -y update
 - sudo apt-get -y install subversion make
 #- sudo apt-get -y install swig libedit-dev subversion make python-dev

install:
 - ./build.sh # setup

before_script:
 - true
 # ./build.sh # update

script:
 - file $PREFIX/bin/clang
 - file $PREFIX/bin/lldb
