language: cpp

sudo: false

compiler:
 - clang

env:
  global:
    - PREFIX: $(pwd)/install
    - JOBS: "12"

# http://docs.travis-ci.com/user/apt/
addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
     - llvm-toolchain-precise-3.5
    packages:
     - subversion
     - time
     - clang-3.5
     - libedit-dev

install:
  # override the travis default CXX which is /usr/local/clang-3.4
 - export CXX="clang++-3.5"
 - export CC="clang-3.5"
 - which $CXX
 - which $CC
 - $CXX --version
 - $CC --version
 - ./build.sh # setup

before_script:
 - true
 # ./build.sh # update

script:
 - if [[ -f $PREFIX/bin/clang ]]; then file $PREFIX/bin/clang; fi;
 - if [[ -f $PREFIX/bin/lldb ]]; then file $PREFIX/bin/lldb; fi;
