language: cpp

sudo: false

env:
  global:
    - PREFIX: $(pwd)/install
    - JOBS: "12"

matrix:
  include:
     # OS X
     - os: osx
       compiler: clang
     # Linux
     - os: linux
       compiler: clang

cache:
  directories:
  - $HOME/.ccache
  apt: true

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
     - llvm-toolchain-precise-3.5
    packages:
     - subversion
     - time
     - clang-3.5
     - libedit-dev

install:
 - if [[ $(uname -s) == 'Linux' ]]; then
     export CXX="ccache clang++-3.5 -Qunused-arguments";
     export CC="ccache clang-3.5 -Qunused-arguments";
     git clone --depth=1 git://github.com/martine/ninja.git;
     cd ninja;
     export PATH=$(pwd):${PATH};
     ./configure.py --bootstrap;
     cd ../;
   else
     brew install ninja;
   fi
 - ./build.sh # setup

before_script:
 - true
 # ./build.sh # update

script:
 - if [[ -f $PREFIX/bin/clang ]]; then file $PREFIX/bin/clang; fi;
 - if [[ -f $PREFIX/bin/lldb ]]; then file $PREFIX/bin/lldb; fi;
